server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zmr
    password: zmr123456
    url: jdbc:mysql://192.168.124.22:3306/voteDmo?serverTimezone=GMT%2b8
mybatis:
  mapper-locations: classpath:mapper/*.xml # scan all mybatis XML files
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # print sql