server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zmr
    password: zmr123456
    url: jdbc:mysql://192.168.124.22:3306/voteDemo?serverTimezone=GMT%2b8
  security:
    user:
      name: wangZiDianXia
      password: handsome123
      roles: USER_ROLE
  web:
    resources:
      static-locations: classpath:/static/
mybatis:
  mapper-locations: classpath:mapper/*.xml # scan all mybatis XML files
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # print sql
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG